#!/usr/bin/python
#-*- coding: utf-8 -*-
#
#       MakeDesktopShortcuts
#
#       Copyright 2011 Francesco Mondello <faster3ck@gmail.com>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

import os
import sys

def main():
    i = 1

    while i < len(sys.argv):
	path =  sys.argv[i]
	if os.path.isdir(path):
	    createDesktopFile(path)
	i = i + 1
    
def extractIconName(path):
    desktopFile = path+"/.directory"
    icon = "folder"
    
    if os.path.isfile(desktopFile):
        f = open(desktopFile, "r")
        lines = f.readlines()
        
        for line in lines:
            if line[0:4] == "Icon":
                icon = line[5:len(line)-1]
                break
                
    return icon
    
def createDesktopFile(path):
    data = "[Desktop Entry]\nEncoding=UTF-8\n"
    data += "Name=%s\n" % os.path.basename(path)
    data += "URL[$e]=%s\n" % path
    data += "Icon=%s\n" % extractIconName(path)
    data += "Type=Link\n"
    data += "OnlyShowIn=KDE;"
    
    desktopFile = "%s.desktop" % os.path.basename(path)
    fileName = "%s/%s" % (os.path.join(os.path.expanduser("~"), "Desktop"),  desktopFile)
    
    try:
        saveData = open(fileName,  "w")
        saveData.write(data)
    except:
        print "Error!"
    
main()
